### ISSUE TITLE
irreptables is not upgrading

### ISSUE THREAD

**Issue by bmondal94** [irreducible-representations/irrep#81]
Dear @stepan-tsirkin @MIraola ,

Sorry...

irreptables is still not upgrading to latest version when installing irrep. Earlier I re-installed irreptables with git clone. So, I missed to catch the problem then. Tried a few options. 

- Added irreptables version condition in irrep setup.py => not working
- As it was already pointed out earlier, irreptables is not a subpackage, this makes upgrading failed.
- Tried to use condition in `irrep setup.py` <= not working
 ```
+import subprocess
+import sys, os
+import pkg_resources
+
+# Function to check and install the required version of irreptables
+def check_and_install_irreptables():
+    try:
+        # Check if irreptables is already installed
+        installed_version = pkg_resources.get_distribution('irreptables').version
+        if installed_version < '1.1.0':
+            raise pkg_resources.DistributionNotFound
+    except pkg_resources.DistributionNotFound:
+        # Install irreptables from local path if it's not installed or needs an update
+        subprocess.check_call([sys.executable, '-m', 'pip', 'install', f'irreptables @ file://{os.path.abspath("irreptables")}'])
+check_and_install_irreptables()
...
```
- pip install irreptables==1.1.0
```
ERROR: Ignored the following yanked versions: 1.0.2
ERROR: Could not find a version that satisfies the requirement irreptables==1.1.0 (from versions: 1.0.0, 1.0.1, 1.0.3)
ERROR: No matching distribution found for irreptables==1.1.0
```

So far, cloning `irrep` locally, going into `irreptables` and then using `pip install .` is working.

Could not come up with any other solution.

**Comment by bmondal94** [comment]
@stepan-tsirkin 
Ha Ha...
- `irreptables-1.1.0` is required to be released in PyPI.
- Recommendation adding `irreptables>=1.1.0` in `irrep setup.py`

**Comment by bmondal94** [comment]
Minor: The `url` in `irreptables setup.py` can be updated to latest url.

**Comment by stepan-tsirkin** [comment]
@bmondal94 , you are right, new irreptables is not released. We did not update it for a long time, and I forgot that @MIraola did not have permissions to upload that package to pypi.

@MIraola , I invited you to that repo on pypi, so please upload irreptables there.

**Comment by MIraola** [comment]
Hi @bmondal94 and @stepan-tsirkin ,

thank you for the invitation to the pypi repository. I have updated `irreptables` there. I have installed `irrep` via `pip install irrep` in a new environment created from scratch and it correctly installed `irreptables=1.1.0` (the version I had just uploaded to pypi). So, it seems it is fixed.

**Comment by MIraola** [comment]
Let me know if we can close the comment, please.

**Comment by bmondal94** [comment]
Hi @MIraola 

Thanks. Perfect.

Just a reminder in case you have not implemented it yet, before the next `irrep` release it would be great if you could add `irreptables>=1.1.0` version requirement in `irrep` `setup.py`, otherwise irrep __upgrading__ would ignore upgrading already installed old `irreptables`.
